global using Shiny;
global using Shiny.Mediator;
global using System;
global using System.Collections.ObjectModel;
global using System.Reactive.Linq;
global using Microsoft.Extensions.Logging;
global using BeatTheBank.Models;
global using BeatTheBank.Services;
global using BeatTheBank.Contracts;
